# Generated by Django 3.2.3 on 2021-05-29 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Categoría')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre Categoría')),
            ],
        ),
        migrations.CreateModel(
            name='TipoAlimento',
            fields=[
                ('idTipo', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Tipo Alimento')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Tipo Alimento')),
            ],
        ),
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('idAlimento', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Alimento')),
                ('nombre', models.CharField(max_length=50, verbose_name='Alimento')),
                ('precio', models.IntegerField(max_length=5, verbose_name='Precio')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafeteria.categoria')),
                ('tipoAlimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafeteria.tipoalimento')),
            ],
        ),
    ]
