# Generated by Django 3.2.3 on 2021-05-29 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='precio',
            field=models.IntegerField(verbose_name='Precio'),
        ),
    ]
