# Generated by Django 3.2.3 on 2021-05-29 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0002_alter_alimento_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimento',
            name='descripcion',
            field=models.CharField(default=None, max_length=100, verbose_name='Descripcion Alimento'),
        ),
    ]
