# Generated by Django 3.2.3 on 2021-05-29 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0003_alimento_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='descripcion',
            field=models.CharField(max_length=100, verbose_name='Descripcion Alimento'),
        ),
    ]
