# Generated by Django 3.2.3 on 2021-06-03 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0004_alter_alimento_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='postulacionConcurso',
            fields=[
                ('idPostulacion', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Postulacion')),
                ('nombreAlimento', models.CharField(max_length=50, verbose_name='Alimento')),
                ('descripcionAlimento', models.CharField(max_length=100, verbose_name='Descripcion Alimento')),
                ('precioAlimento', models.IntegerField(verbose_name='Precio')),
            ],
        ),
    ]
